const ROOM_DATA_REQUEST = "ROOM_DATA_REQUEST";
const ROOM_DATA_SUCCESS = "ROOM_DATA_SUCCESS";
const ROOM_DATA_FAILURE = "ROOM_DATA_FAILURE";

export { ROOM_DATA_REQUEST, ROOM_DATA_SUCCESS, ROOM_DATA_FAILURE };
