export const CREATE_ENQUIRY_REQUEST = "CREATE_ENQUIRY_REQUEST";
export const CREATE_ENQUIRY_SUCCESS = "CREATE_ENQUIRY_SUCCESS";
export const CREATE_ENQUIRY_FAILURE = "CREATE_ENQUIRY_FAILURE";
export const UPDATE_ENQUIRY_FORM_OBJ = "UPDATE_ENQUIEY_FORM_OBJ";
export const UPDATE_ENQUIRY_DIALOUGE_OBJ = "UPDATE_ENQUIRY_DIALOUGE_OBJ";
export const HIDE_SUCCESS_NOTIFICATION = "HIDE_SUCCESS_NOTIFICATION";
export const HIDE_FAILURE_NOTIFICATION = "HIDE_FAILURE_NOTIFICATION";
